metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"

rpc_bind_addr = "0.0.0.0:3901"
rpc_secret = "deadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef"

replication_factor = 1
block_size = 5242880

[s3_api]
bind_addr = "0.0.0.0:3900"
s3_region = "garage"

[admin]
bind_addr = "0.0.0.0:3903"

[nodes]
node1 = {}
