import { buildJobs, deployments } from "@shipyard/shared/schema";
import { desc, eq } from "drizzle-orm";
import { db } from "../plugins/db.js";

const safeColumns = {
	id: deployments.id,
	appId: deployments.appId,
	commitSha: deployments.commitSha,
	commitMessage: deployments.commitMessage,
	branch: deployments.branch,
	status: deployments.status,
	detectedFramework: deployments.detectedFramework,
	outputDir: deployments.outputDir,
	startedAt: deployments.startedAt,
	finishedAt: deployments.finishedAt,
	createdAt: deployments.createdAt,
};

/**
 * Creates a deployment and its initial build job in a single transaction.
 *
 * Both inserts succeed or fail atomically. If the transaction commits but
 * the caller fails to enqueue the queue job (e.g. Redis down), the rows
 * exist in the database and will be picked up when Redis recovers.
 *
 * @param appId - The app to deploy
 * @returns The created deployment (ID auto-generated by DB)
 */
export async function createDeploymentWithBuildJob(appId: string) {
	return db.transaction(async (tx) => {
		const [deployment] = await tx
			.insert(deployments)
			.values({ appId })
			.returning();

		await tx.insert(buildJobs).values({
			deploymentId: deployment.id,
			step: "pending",
			status: "pending",
		});

		return deployment;
	});
}

/**
 * Lists deployments for an app, newest first.
 *
 * @param appId - The app to list deployments for
 * @returns Array of deployment objects
 */
export async function listDeployments(appId: string) {
	return db
		.select(safeColumns)
		.from(deployments)
		.where(eq(deployments.appId, appId))
		.orderBy(desc(deployments.createdAt));
}

/**
 * Gets a single deployment by ID.
 *
 * @param deploymentId - The deployment ID
 * @returns The deployment or null if not found
 */
export async function getDeployment(deploymentId: string) {
	const rows = await db
		.select(safeColumns)
		.from(deployments)
		.where(eq(deployments.id, deploymentId));
	return rows[0] ?? null;
}
