import {
	apps,
	buildJobs,
	deploymentLogs,
	deployments,
} from "@shipyard/shared/schema";
import { asc, desc, eq } from "drizzle-orm";
import { db } from "../plugins/db.js";

const safeColumns = {
	id: deployments.id,
	appId: deployments.appId,
	commitSha: deployments.commitSha,
	commitMessage: deployments.commitMessage,
	branch: deployments.branch,
	status: deployments.status,
	detectedFramework: deployments.detectedFramework,
	outputDir: deployments.outputDir,
	startedAt: deployments.startedAt,
	finishedAt: deployments.finishedAt,
	prunedAt: deployments.prunedAt,
	createdAt: deployments.createdAt,
};

/**
 * Creates a deployment and its initial build job in a single transaction.
 *
 * Both inserts succeed or fail atomically. If the transaction commits but
 * the caller fails to enqueue the queue job (e.g. Redis down), the rows
 * exist in the database and will be picked up when Redis recovers.
 *
 * @param appId - The app to deploy
 * @returns The created deployment (ID auto-generated by DB)
 */
export async function createDeploymentWithBuildJob(appId: string) {
	return db.transaction(async (tx) => {
		const [deployment] = await tx
			.insert(deployments)
			.values({ appId })
			.returning();

		await tx.insert(buildJobs).values({
			deploymentId: deployment.id,
			step: "pending",
			status: "pending",
		});

		return deployment;
	});
}

/**
 * Lists deployments for an app, newest first, along with the app's active
 * deployment ID so the frontend can highlight which deployment is live.
 *
 * @param appId - The app to list deployments for
 * @returns Object containing deployments array and activeDeploymentId
 */
export async function listDeployments(appId: string) {
	const [app] = await db
		.select({ activeDeploymentId: apps.activeDeploymentId })
		.from(apps)
		.where(eq(apps.id, appId));

	const list = await db
		.select(safeColumns)
		.from(deployments)
		.where(eq(deployments.appId, appId))
		.orderBy(desc(deployments.createdAt));

	return {
		deployments: list,
		activeDeploymentId: app?.activeDeploymentId ?? null,
	};
}

/**
 * Gets a single deployment by ID.
 *
 * @param deploymentId - The deployment ID
 * @returns The deployment or null if not found
 */
export async function getDeployment(deploymentId: string) {
	const rows = await db
		.select(safeColumns)
		.from(deployments)
		.where(eq(deployments.id, deploymentId));
	return rows[0] ?? null;
}

/**
 * Returns structured log events for a deployment, oldest first.
 *
 * @param deploymentId - The deployment to fetch logs for
 * @returns Array of deployment log entries
 */
export async function getDeploymentLogs(deploymentId: string) {
	return db
		.select()
		.from(deploymentLogs)
		.where(eq(deploymentLogs.deploymentId, deploymentId))
		.orderBy(asc(deploymentLogs.createdAt));
}

export async function rollbackDeployment(
	deploymentId: string,
	orgId: string,
): Promise<{
	deployment: typeof deployments.$inferSelect | null;
	app: typeof apps.$inferSelect | null;
}> {
	const deployment = await getDeployment(deploymentId);
	if (!deployment) return { deployment: null, app: null };
	if (deployment.status !== "success") {
		throw Object.assign(
			new Error(
				`Cannot rollback: deployment has status "${deployment.status}"`,
			),
			{ statusCode: 422 },
		);
	}
	if (deployment.prunedAt) {
		throw Object.assign(
			new Error("Cannot rollback: deployment artifacts have been pruned"),
			{ statusCode: 410 },
		);
	}

	const [app] = await db
		.select()
		.from(apps)
		.where(eq(apps.id, deployment.appId));
	if (!app || app.organizationId !== orgId) {
		return { deployment: null, app: null };
	}

	if (app.activeDeploymentId === deployment.id) {
		throw Object.assign(new Error("Deployment is already active"), {
			statusCode: 409,
		});
	}

	return { deployment, app } as {
		deployment: typeof deployments.$inferSelect | null;
		app: typeof apps.$inferSelect | null;
	};
}
